### ISSUE TITLE
Create follow/subscribe handler

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaForum#14]
## Summary

From the spec:
```
follow:
  input: -
  action: create "follow" event
  return the list of 20 latest events (all but follow)
  remark: one can follow which is opened or closed
```

## Requirements

- [x] Add/Update a method on forum table to return x last elements
- [x] Test added/updated methods on the forum table
- [x] Create the follow/subscribe handler
- [x] Test the follow/subscribe handler
