### ISSUE TITLE
Create unfollow handler

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaForum#19]
## Summary

From the spec:
```
unfollow:
  input: -
  action: remove "follow" event
  return: -
```

## Requirements

- [x] Update table to allow 'remove' operation
- [x] Test table 'remove' operation
- [x] Create handler
- [x] Test handler
- [ ] After-review additional treatment: send an `unfollow` message to other followers (not self of course).
